export const youtubeData = [
  {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl:
      "https://i.ytimg.com/vi/vz1RlUyrc3w/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCPuqXVkPj7ttWHlhfi9QZ8hFdqug",
    description: "A quick tutorial to get started with React.",
    channelId: "channel01",
    uploader: "Chai aur Code",
    views: "1M",
    likes: "26K",
    dislikes: "45",
    uploadDate: "1 year ago",
    genre: "Education",
    videoUrl: "https://www.youtube.com/watch?v=vz1RlUyrc3w&t=61s",
    comments: [
      {
        commentId: "comment01",
        userId: "user02",
        text: "Great video! Very helpful.",
        timestamp: "oct 20 ,2023",
      },
    ],
  },
  {
    videoId: "video02",
    title: "  React Js Tutorials in Hindi",
    thumbnailUrl:
      "https://i.ytimg.com/vi/-mJFZp84TIY/hqdefault.jpg?s%E2%80%A6RUAAIhCGAE=&rs=AOn4CLDHBmNMkrlki0bJx7dkyaYw7lu7sQ",
    description: "Matsering in react js and redux tool kit.",
    channelId: "channel02",
    uploader: "CodeWithHarry",
    views: "3.7M",
    likes: "26K",
    dislikes: "125",
    uploadDate: "3 years ago",
    genre: "Education",
    videoUrl: "https://www.youtube.com/watch?v=-mJFZp84TIY&t=2s",
    comments: [
      {
        commentId: "comment02",
        userId: "user02",
        text: "He's back when the world needed him the most ❤️",
        timestamp: " Aug 13, 2021",
      },
    ],
  },
  {
    videoId: "video03",
    title: " OTP The Lottery:chapter 1",
    thumbnailUrl:
      "https://i.ytimg.com/vi/-O7a9Oro1KI/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCgBal4URSBNgyMqLJ8sJdqqJ22TA",
    description: "a great comedy video based hilarious sequence.",
    channelId: "channel03",
    uploader: "ashish chanchlani vines",
    views: "55M",
    likes: "3.5M",
    dislikes: "8K",
    uploadDate: "3 years ago",
    genre: "Comedy",
    videoUrl: "https://www.youtube.com/watch?v=-O7a9Oro1KI&t=11s",
    comments: [
      {
        commentId: "comment03",
        userId: "user03",
        text: "Starting 🔥 Ashish Chanchlani Acting & Carry Minati Voice 😍 Mja Aa Gya 🚩",
        timestamp: "Jun 30, 2021",
      },
    ],
  },
  {
    videoId: "video04",
    title: "Daaru With Dad 3 ",
    thumbnailUrl:
      "https://i.ytimg.com/vi/220TpHgDfvs/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCQGEyRTerAa8i3IbQsjwQFe_anJA",
    description: "comedy with son and many more",
    channelId: "channel04",
    uploader: "Harsh Beniwal",
    views: "32M",
    likes: "2.2M",
    dislikes: "5K",
    uploadDate: "2 years ago",
    genre: "Comedy",
    videoUrl: "https://www.youtube.com/watch?v=220TpHgDfvs&t=1324s",
    comments: [
      {
        commentId: "comment04",
        userId: "user04",
        text: "Harsh Beniwal and Purav Jha is one of the Best Duo ❤️😌 Loved their chemistry 😂",
        timestamp: "  May 24, 2022",
      },
    ],
  },
  {
    videoId: "video05",
    title: "Top 100 News LIVE",
    thumbnailUrl:
      "https://i.ytimg.com/vi/bQ-idFyWaoA/hq720.jpg?v=675%E2%80%A6BACGAY4AUAB&rs=AOn4CLBHxnj6ehbJ-yaV6xFdE0OaDKWxmg",
    description: "Top 100 news live and other news",
    channelId: "channel5",
    uploader: "ABP NEWS",
    views: "2k",
    likes: "566",
    dislikes: "87",
    uploadDate: "6 hours ago",
    genre: "News",
    videoUrl: "https://www.youtube.com/watch?v=bQ-idFyWaoA",
    comments: [
      {
        commentId: "comment05",
        userId: "user05",
        text: "good one",
        timestamp: " 6 hours ago",
      },
    ],
  },
  {
    videoId: "video06",
    title: "Top 100 News LIVE",
    thumbnailUrl:
      "https://i.ytimg.com/vi/RILJ1FbFLXU/hq720.jpg?v=675%E2%80%A6BACGAY4AUAB&rs=AOn4CLDbhqBgTk4O0lxNv2AJ7Hjpt8Z4ig",
    description: "Top 100 news live ",
    channelId: "channel6",
    uploader: "News18 India",
    views: "800",
    likes: "300",
    dislikes: "78",
    uploadDate: "14 hours ago",
    genre: "News",
    videoUrl: "https://www.youtube.com/watch?v=RILJ1FbFLXU",
    comments: [
      {
        commentId: "comment06",
        userId: "user06",
        text: "great,it's a good  news channel",
        timestamp: " 14 hours ago",
      },
    ],
  },
  {
    videoId: "video07",
    title: "AJJUBHAI FIRST TIME PLAYING BGMI AFTER UNBAN",
    thumbnailUrl:
      "https://i.ytimg.com/vi/5Cc9MBrvgAo/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDyufAgc6c-T-DpLBeBdMIZICioEw",
    description: "gaming with friends ",
    channelId: "channel7",
    uploader: "Total Gaming",
    views: "4M",
    likes: "341K",
    dislikes: "12K",
    uploadDate: "1 year ago",
    genre: "Gaming",
    videoUrl: "https://www.youtube.com/watch?v=5Cc9MBrvgAo",
    comments: [
      {
        commentId: "comment07",
        userId: "user07",
        text: "Congratulations for 35M 🎉",
        timestamp: "Jun 2, 2023",
      },
    ],
  },
  {
    videoId: "video08",
    title: "Scout & Triggered Insaan VS. Valorant PROS 😲 | Gaming Insaan",
    thumbnailUrl:
      "https://i.ytimg.com/vi/lkBlgKFHHxA/hqdefault.jpg?s%E2%80%A6BACGAY4AUAB&rs=AOn4CLCIC539tuMopWVZiDa-r5-T_DS28w",
    description: "playing game with friends",
    channelId: "channel8",
    uploader: "Scout",
    views: "66K",
    likes: "7.3K",
    dislikes: "900",
    uploadDate: "1 month ago",
    genre: "Gaming",
    videoUrl: "https://www.youtube.com/watch?v=lkBlgKFHHxA",
    comments: [
      {
        commentId: "comment08",
        userId: "user08",
        text: "Scoutop and Triggered Insaan ⚡⚡",
        timestamp: "nov 2, 2024",
      },
    ],
  },
  {
    videoId: "video09",
    title: "When Indians go to EUROPE || Hum Chale Greece 😃",
    thumbnailUrl:
      "https://i.ytimg.com/vi/jkviE5AMaFA/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCs30ju6A6kbbzxjMd8x2NwK7MUEQ ",
    description: "Most spontaneous trip to #EUROPE!",
    channelId: "channel9",
    uploader: "Wanderers Hub",
    views: "2.8M",
    likes: "70K",
    dislikes: "680",
    uploadDate: "1 year ago",
    genre: "Travel",
    videoUrl: "https://www.youtube.com/watch?v=jkviE5AMaFA",
    comments: [
      {
        commentId: "comment09",
        userId: "user09",
        text: "This kid had travelled more than I could have in my entire life...🙂😂💙",
        timestamp: " Oct 26, 2023",
      },
    ],
  },
  {
    videoId: "video10",
    title:
      "SAN FRANCISCO TRAVEL VLOG 🇺🇸 Indian Girl Traveling Solo in San Francisco, USA | Kritika Goel",
    thumbnailUrl:
      "https://i.ytimg.com/vi/i9cXZK9rQgg/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC6Z89jDbM429zqU7Lr6vxIjOyEeg",
    description:
      "Explored San Francisco solo and even though it was my second time here, I absolutely loved the city! In this travel vlog, I spent 3 days in San Francisco, and show you some of the best things to do in San Francisco",
    channelId: "channel10",
    uploader: "Kritika Goel",
    views: "112K",
    likes: "70K",
    dislikes: "680",
    uploadDate: "1 year ago",
    genre: "Travel",
    videoUrl: "https://www.youtube.com/watch?v=i9cXZK9rQgg",
    comments: [
      {
        commentId: "comment10",
        userId: "user10",
        text: "Watching much-waited San Francisco through your lens has treated my soul with joy",
        timestamp: "   May 7, 2023 ",
      },
    ],
  },
  {
    videoId: "video11",
    title:
      "Thrills in Costa Rican Wild|Running Wild With Bear Grylls: The Challenge",
    thumbnailUrl:
      "https://i.ytimg.com/vi/tJBJa_q-4qY/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCyNaJjVNlUIACphIQxqv_jqw33Aw",
    description:
      "In Running Wild with Bear Grylls: The Challenge, Ashton Kutcher teams up with Bear to tackle the rugged coastal jungles of Costa Rica. Their thrilling adventure starts with a daring helicopter jumping into the Pacific Ocean, setting the stage for an exhilarating exploration of survival and teamwork in the wild.",
    channelId: "channel11",
    uploader: "National Geographic India",
    views: "112K",
    likes: "12K",
    dislikes: "2.5K",
    uploadDate: "1 month ago",
    genre: "Adventure",
    videoUrl: "https://www.youtube.com/watch?v=tJBJa_q-4qY",
    comments: [
      {
        commentId: "comment11",
        userId: "user11",
        text: "My childhood hero is back again 😀",
        timestamp: " Oct 17, 2024 ",
      },
    ],
  },
  {
    videoId: "video12",
    title: "Bear Grylls’ Wildest Things Eaten | Man vs. Wild | Discovery",
    thumbnailUrl:
      "https://i.ytimg.com/vi/ZyHWTdXeZ0E/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAUmo5VCel5ELBVEJ4iwVwCEW6K3w",
    description:
      "Watch Bear Grylls take on the wildest survival meals, from scorpions and goat testicles to his own urine. These daring choices showcase the extreme lengths he'll go to stay alive in the harshest environments",
    channelId: "channel12",
    uploader: "Discovery",
    views: "228K",
    likes: "12K",
    dislikes: "2.5K",
    uploadDate: "2 weeks ago",
    genre: "Adventure",
    videoUrl: "https://www.youtube.com/watch?v=ZyHWTdXeZ0E",
    comments: [
      {
        commentId: "comment12",
        userId: "user12",
        text: "I love how he describes his eating experiences with much detail.",
        timestamp: "Nov 21, 2024 ",
      },
    ],
  },
  {
    videoId: "video13",
    title: "The Epic Montage | T20 World Cup 2024 Final",
    thumbnailUrl:
      "https://i.ytimg.com/vi/3yiWqnKl7lQ/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDJ9BWaUy03_fYe9i0TBFRH0yRWbw",
    description: "Every emotion, every angle 😲👀",
    channelId: "channel13",
    uploader: "ICC",
    views: "6.3M",
    likes: "195K",
    dislikes: "570",
    uploadDate: "5 months ago",
    genre: "Cricket",
    videoUrl: "https://www.youtube.com/watch?v=3yiWqnKl7lQ&t=33s",
    comments: [
      {
        commentId: "comment13",
        userId: "user13",
        text: "The Moment when Surya took the stunner cheer and roar from crowd next level 🔥🔥. India broke the Jinx in style 🙌",
        timestamp: " Jul 4, 2024",
      },
    ],
  },
  {
    videoId: "video14",
    title: "Virat Kohli's game-changing knock | IND v PAK | T20WC 2022",
    thumbnailUrl:
      "https://i.ytimg.com/vi/_CFS5uZCcTw/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAPWArM0yunlHSAFv6Nl4QIMFDyBA",
    description: "Re-live Kohli's epic masterpiece 🎥",
    channelId: "channel14",
    uploader: "ICC",
    views: "5.6M",
    likes: "142K",
    dislikes: "780",
    uploadDate: "1 month ago",
    genre: "Cricket",
    videoUrl: "https://www.youtube.com/watch?v=_CFS5uZCcTw",
    comments: [
      {
        commentId: "comment14",
        userId: "user14",
        text: "Dhoni finishes off in style and kohli goes down the ground will remain in our hearts forever ❤",
        timestamp: " Oct 23, 2024  ",
      },
    ],
  },
  {
    videoId: "video15",
    title: "Avengers: Endgame (2019) - ''The Big Three'' | Movie Clip HD",
    thumbnailUrl:
      "https://i.ytimg.com/vi/XpeOIww_l4A/hqdefault.jpg?sqp=-oaymwEnCOADEI4CSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBE22SfPa25O4jveT25oYTnTIjelg%22",
    description: "#avengers endgame",
    channelId: "channel15",
    uploader: "Marvel Universe Entertainment",
    views: "28M",
    likes: "272K",
    dislikes: "780",
    uploadDate: "5 years ago",
    genre: "Movies",
    videoUrl: "https://www.youtube.com/watch?v=XpeOIww_l4A",
    comments: [
      {
        commentId: "comment15",
        userId: "user15",
        text: "Thanos' voice, the way he delivered the lines... Man, Josh did an amazing job with this",
        timestamp: " Aug 23, 2019  ",
      },
    ],
  },
  {
    videoId: "video16",
    title: "The Sorting Ceremony | Harry Potter and the Philosopher's Stone",
    thumbnailUrl:
      "https://i.ytimg.com/vi/z4K2F_OALPQ/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLD1bHkPx6HQsQ1x0iscXpDPgIGtUQ",
    description:
      "The first-year Hogwarts School of Witchcraft and Wizardry students are assigned their houses at the annual Sorting Ceremony",

    channelId: "channel16",
    uploader: "Harry Potter",
    views: "24M",
    likes: "3M",
    dislikes: "128K",
    uploadDate: "7 years ago",
    genre: "Movies",
    videoUrl: "https://www.youtube.com/watch?v=XpeOIww_l4A",
    comments: [
      {
        commentId: "comment16",
        userId: "user16",
        text: "All time fav movie!!",
        timestamp: " Jun 27, 2017 ",
      },
    ],
  },
  {
    videoId: "video17",
    title: "Ed Sheeran - Perfect (Official Music Video)",
    thumbnailUrl:
      "https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg?sqp=-oaymwEnCOADEI4CSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLB62wLli1iI_M1zTBRAeTBbje6zNg",
    description: "The official music video for Ed Sheeran - Perfect",

    channelId: "channel17",
    uploader: "Ed Sheeran",
    views: "3.8B",
    likes: "22M",
    dislikes: "196K",
    uploadDate: "7 years ago",
    genre: "Music",
    videoUrl: "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    comments: [
      {
        commentId: "comment17",
        userId: "user17",
        text: "If you're not in love, this song makes you remember when you were-- wonderfully nostalgic. Timeless.",
        timestamp: "  Nov 9, 2017 ",
      },
    ],
  },
  {
    videoId: "video18",
    title: "One Direction - Night Changes",
    thumbnailUrl:
      "https://i.ytimg.com/vi/syFZfO_wfMQ/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBNuv8q0wdhJz2As0lRC79v3ZrH4Q",
    description: "One Direction – Night Changes (Official Video)",

    channelId: "channel18",
    uploader: "OneDirectionVEVO",
    views: "909M",
    likes: "8.4M",
    dislikes: "234K",
    uploadDate: "10 years ago",
    genre: "Music",
    videoUrl: "https://www.youtube.com/watch?v=syFZfO_wfMQ",
    comments: [
      {
        commentId: "comment18",
        userId: "user18",
        text: "This song hits different now🥹",
        timestamp: "   Nov 21, 2014 ",
      },
    ],
  },
];
